name: Release CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install UI dependencies
        run: npm ci
      - name: Build
        run: npm run build
